version: "3.8"
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 6543:6543
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
